// Source Catalog — every data pipeline this dashboard knows about.
// Status is what an engineer needs to ship the layer:
//   live      — adapter wired, endpoint working, no key required (or key shipped via env)
//   ready     — adapter scaffolded; flip a switch / drop a key to go live
//   planned   — known endpoint, no adapter yet; one afternoon of work
//   research  — we know the data exists but not the public endpoint
//
// Categories drive the "Source Catalog" panel groupings.

// "stub" — adapter file exists + returns mock data; waiting for a real data
//           source / partnership before going live
export type SourceStatus = "live" | "ready" | "planned" | "research" | "stub";

export type SourceCategory =
  | "mobility"      // traffic, transit, shuttle
  | "incidents"     // citizen reports, traffic events
  | "environment"   // weather, air, water, vegetation
  | "imagery"       // satellite, aerial, CCTV
  | "vibes"         // news, social, search trends
  | "infrastructure" // utilities, parking, energy
  | "maritime"      // AIS, ports, lighthouses, ferries
  | "open-data"     // data.go.th and adjacent national/local portals
  | "campus";       // legacy — kept for backward compat

export interface SourceEntry {
  id: string;
  label: string;
  vendor: string;
  category: SourceCategory;
  status: SourceStatus;
  endpoint?: string;     // URL or pattern
  apiPath?: string;      // path served by our API (when live)
  keyEnv?: string;       // env var name if a key is required
  pollSeconds?: number;
  describe: string;      // 1-line, engineer-readable
  docs?: string;
}

export const SOURCE_CATALOG: SourceEntry[] = [
  // ---- Mobility ----
  {
    id: "itic-longdo",
    label: "iTIC / Longdo traffic events",
    vendor: "iTIC + Longdo Map",
    category: "mobility",
    status: "live",
    endpoint: "https://event.longdo.com/feed/json",
    apiPath: "/api/incidents/itic",
    pollSeconds: 180,
    describe: "Accidents, closures, construction, congestion events with lat/lng + severity.",
    docs: "https://map.longdo.com/products/traffic",
  },
  {
    id: "longdo-cameras",
    label: "Longdo CCTV cameras",
    vendor: "Longdo Map",
    category: "imagery",
    status: "ready",
    endpoint: "https://camera.longdo.com/feed/?command=json",
    apiPath: "/api/cctv/longdo",
    pollSeconds: 300,
    describe: "Hundreds of street CCTV with JPG/HLS streams; filter to the Nakhon Si Thammarat bbox (Old Town / Ratchadamnoen axis) for the local set.",
    docs: "https://camera.longdo.com",
  },
  {
    id: "highways-th",
    label: "Department of Highways cameras",
    vendor: "Thai Department of Highways",
    category: "imagery",
    status: "research",
    endpoint: "https://highway.dxc-thailand.com/",
    describe: "Highway 401/403/408 cameras around Nakhon Si Thammarat; useful if we extend the bbox to the Tha Sala / Sichon approaches.",
  },
  {
    id: "srt-southern-line",
    label: "SRT Southern Line stations",
    vendor: "State Railway of Thailand",
    category: "mobility",
    status: "planned",
    endpoint: "https://data.go.th/dataset/srt-stations",
    describe: "Static station GeoJSON for the Southern Line through Nakhon Si Thammarat (Khao Chum Thong junction, NST terminus); timetable scrape when feed located.",
    docs: "https://www.railway.co.th/",
  },
  {
    id: "google-traffic",
    label: "Google Maps traffic raster",
    vendor: "Google",
    category: "mobility",
    status: "planned",
    keyEnv: "GOOGLE_MAPS_KEY",
    describe: "Tile overlay; commercial license required. Use as a fallback comparison to iTIC + simulated heatmap.",
  },
  {
    id: "tomtom-traffic",
    label: "TomTom traffic flow",
    vendor: "TomTom",
    category: "mobility",
    status: "planned",
    keyEnv: "TOMTOM_KEY",
    describe: "Free 2,500 req/day tier; per-segment speed vs. free-flow — good replacement for simulated heatmap.",
    docs: "https://developer.tomtom.com/traffic-api",
  },
  {
    id: "here-traffic",
    label: "HERE traffic flow + incidents",
    vendor: "HERE Technologies",
    category: "mobility",
    status: "planned",
    keyEnv: "HERE_API_KEY",
    describe: "Per-link jam factor JSON; free tier 250k req/month.",
    docs: "https://developer.here.com/",
  },

  // ---- Incidents ----
  {
    id: "traffy-fondue",
    label: "Traffy Fondue citizen reports",
    vendor: "NECTEC",
    category: "incidents",
    status: "live",
    endpoint: "https://publicapi.traffy.in.th/dump-csv-stat-bma/bangkok_traffy.json",
    apiPath: "/api/incidents/city-reports",
    pollSeconds: 300,
    describe: "National citizen complaint feed (potholes, flooding, waste, lighting); bbox-filtered to Nakhon Si Thammarat city + the Pak Phanang basin.",
    docs: "https://www.traffy.in.th/",
  },
  {
    id: "city-reporter-v2",
    label: "City Reporter v2 (own intake)",
    vendor: "Dr Non — internal",
    category: "incidents",
    status: "planned",
    apiPath: "/api/incidents/internal",
    describe: "LINE/Telegram intake writing to Supabase; same shape as Traffy. Drop in when the municipality wants its own channel.",
  },

  // ---- Environment ----
  {
    id: "open-meteo",
    label: "Open-Meteo weather + forecast",
    vendor: "Open-Meteo",
    category: "environment",
    status: "live",
    endpoint: "https://api.open-meteo.com/v1/forecast",
    apiPath: "/api/weather",
    pollSeconds: 1800,
    describe: "No-key weather: current + 7d hourly. Used for KPI strip; also for rain prediction overlay later.",
  },
  {
    id: "open-meteo-aq",
    label: "Open-Meteo air quality grid",
    vendor: "Open-Meteo",
    category: "environment",
    status: "live",
    endpoint: "https://air-quality-api.open-meteo.com/v1/air-quality",
    apiPath: "/api/air-quality",
    pollSeconds: 900,
    describe: "US AQI + PM2.5/PM10 from Copernicus reanalysis grid. Free, no key.",
  },
  {
    id: "air4thai",
    label: "Air4Thai — PCD stations (Nakhon Si Thammarat / Southern)",
    vendor: "Pollution Control Department",
    category: "environment",
    status: "live",
    endpoint: "http://air4thai.pcd.go.th/services/getNewAQI_JSON.php",
    apiPath: "/api/air-quality/air4thai",
    pollSeconds: 1800,
    describe: "Official Thai government AQ monitors filtered to Nakhon Si Thammarat province and nearby Southern stations. Public, no key, HTTP only (expired TLS cert). Real PM2.5 + national AQI.",
    docs: "http://air4thai.pcd.go.th/",
  },
  {
    id: "waqi",
    label: "WAQI (World AQI) tiles",
    vendor: "WAQI / EBAS",
    category: "environment",
    status: "planned",
    keyEnv: "WAQI_TOKEN",
    endpoint: "https://api.waqi.info/v2/feed/here/?token={token}",
    describe: "Crowd-sourced AQI with tile overlay; token from waqi.info.",
  },
  {
    id: "openaq",
    label: "OpenAQ historical",
    vendor: "OpenAQ",
    category: "environment",
    status: "planned",
    endpoint: "https://api.openaq.org/v2",
    describe: "Historical air-quality time series; useful for hour-of-day baselines, not realtime.",
  },
  {
    id: "tmd-weather",
    label: "TMD Thai Meteorological Dept.",
    vendor: "TMD",
    category: "environment",
    status: "planned",
    endpoint: "https://data.tmd.go.th/api/Weather3Hours/v1/",
    keyEnv: "TMD_KEY",
    describe: "Free Thai-language forecast with 3-hour granularity. Auth required (register).",
  },
  {
    id: "thaiwater-waterlevel",
    label: "HII ThaiWater — river gauges (26 stations)",
    vendor: "Hydro-Informatics Institute (HII)",
    category: "environment",
    status: "live",
    endpoint: "https://api-v3.thaiwater.net/api/v1/thaiwater30/public/waterlevel",
    apiPath: "/api/water/gauges",
    pollSeconds: 600,
    describe: "26 telemetry water-level stations in NST province (~10-min updates). Carries situation_level (1=drought, 5=overbank/flood) and warning/critical thresholds per station. The primary leading indicator for the Tha Dee / Pak Phanang flood cascade.",
    docs: "https://api-v3.thaiwater.net",
  },
  {
    id: "thaiwater-rain",
    label: "HII ThaiWater — rainfall (130 stations)",
    vendor: "Hydro-Informatics Institute (HII)",
    category: "environment",
    status: "live",
    endpoint: "https://api-v3.thaiwater.net/api/v1/thaiwater30/public/rain_24h",
    apiPath: "/api/water/rain",
    pollSeconds: 1800,
    describe: "130 rainfall telemetry stations across NST province with 1h and 24h accumulations. Drives the FloodPosture composite trigger (observed rain + forecast rain on the JMA/JAXA ladder).",
    docs: "https://api-v3.thaiwater.net",
  },
  {
    id: "dwr-ews",
    label: "DWR Early Warning System (flash-flood / soil)",
    vendor: "Department of Water Resources",
    category: "environment",
    status: "live",
    endpoint: "https://ews.dwr.go.th/ews/web-service/stn",
    apiPath: "/api/water/ews",
    pollSeconds: 900,
    describe: "~86 community flash-flood / landslide stations in NST's Khao Luang headwater districts. Carries an official 0-3 alert status and soil-moisture % — the flash-flood precursor flagged by the Japan-ASEAN flood roundtable. The highest-value signal for upland flash-flood warning.",
    docs: "https://ews.dwr.go.th",
  },
  {
    id: "rid-reservoirs",
    label: "RID reservoirs (Southern / Pak Phanang basin)",
    vendor: "Royal Irrigation Department",
    category: "environment",
    status: "live",
    endpoint: "https://app.rid.go.th/reservoir/api/reservoir/public",
    apiPath: "/api/water/reservoirs-rid",
    pollSeconds: 3600,
    describe: "Reservoir storage, volume, inflow/outflow for NST / Pak Phanang basin reservoirs (ห้วยน้ำใส rsv434, คลองกะทูน rsv435, ยางชุม rsv425). 461 reservoirs nationally; filtered to NST.",
    docs: "https://app.rid.go.th",
  },
  {
    id: "rid-flood",
    label: "RID flood + canal levels (Tha Dee / Pak Phanang)",
    vendor: "Royal Irrigation Department",
    category: "environment",
    status: "planned",
    endpoint: "https://www.rid.go.th/",
    describe: "Canal levels, gates and pump stations for the Tha Dee canal (คลองท่าดี) and the Pak Phanang basin. Used for monsoon flood ops; port adapter when the public feed is located.",
  },
  {
    id: "gistda-flood",
    label: "GISTDA flood extent",
    vendor: "GISTDA",
    category: "environment",
    status: "planned",
    endpoint: "https://flood.gistda.or.th/",
    describe: "Sentinel-1 SAR-derived flood polygons during Thai monsoon. WMS endpoint available.",
  },

  // ---- Imagery ----
  {
    id: "gibs-true-color",
    label: "NASA GIBS true-color (MODIS)",
    vendor: "NASA EOSDIS",
    category: "imagery",
    status: "live",
    endpoint: "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/...",
    apiPath: "(client tile fetch)",
    describe: "1km true-color daily imagery; WMTS tile layer. Free, no key.",
    docs: "https://nasa-gibs.github.io/gibs-api-docs/",
  },
  {
    id: "gibs-ndvi",
    label: "NASA GIBS NDVI",
    vendor: "NASA EOSDIS",
    category: "imagery",
    status: "live",
    endpoint: "https://gibs.earthdata.nasa.gov/wmts/.../MODIS_Terra_NDVI_8Day/...",
    apiPath: "(client tile fetch)",
    describe: "Vegetation index 8-day composite. Useful for tracking Khao Luang forest cover and the urban heat-island gradient over Nakhon Si Thammarat.",
  },
  {
    id: "sentinel-hub",
    label: "Sentinel Hub Process API",
    vendor: "ESA / Sinergise",
    category: "imagery",
    status: "planned",
    keyEnv: "SENTINEL_HUB_CLIENT_ID,SENTINEL_HUB_CLIENT_SECRET",
    endpoint: "https://services.sentinel-hub.com/api/v1/process",
    describe: "10m Sentinel-2 + Sentinel-1 SAR on demand. Free OAuth tier (30k PU/month).",
    docs: "https://docs.sentinel-hub.com/api/latest/",
  },
  {
    id: "gistda-theos",
    label: "GISTDA THEOS-2 / Pleiades",
    vendor: "GISTDA",
    category: "imagery",
    status: "planned",
    describe: "Thai high-res satellite; product order via dict.gistda.or.th, MOU needed for direct API.",
  },
  {
    id: "planetary-computer",
    label: "Microsoft Planetary Computer STAC",
    vendor: "Microsoft",
    category: "imagery",
    status: "planned",
    endpoint: "https://planetarycomputer.microsoft.com/api/stac/v1",
    describe: "STAC catalog + signed tile tokens; great for historical Sentinel/Landsat lookups.",
  },
  {
    id: "jaxa-himawari",
    label: "JAXA Himawari real-time",
    vendor: "JAXA / JMA",
    category: "imagery",
    status: "planned",
    endpoint: "https://www.eorc.jaxa.jp/ptree/index.html",
    describe: "Geostationary cloud loop, 10-min cadence. Use for storm approach.",
  },

  // ---- Vibes ----
  {
    id: "google-news-rss",
    label: "Google News RSS",
    vendor: "Google",
    category: "vibes",
    status: "live",
    endpoint: "https://news.google.com/rss/search?q=...",
    apiPath: "/api/news",
    pollSeconds: 300,
    describe: "Keyword-driven RSS (TH + EN) for นครศรีธรรมราช / Pak Phanang / Khao Luang / Old Town.",
  },
  {
    id: "thaipbs-rss",
    label: "Thai PBS English RSS",
    vendor: "Thai PBS",
    category: "vibes",
    status: "ready",
    endpoint: "https://www.thaipbsworld.com/feed/",
    describe: "Add to /api/news feed list.",
  },
  {
    id: "the-nation-rss",
    label: "The Nation RSS",
    vendor: "Nation Thailand",
    category: "vibes",
    status: "ready",
    endpoint: "https://www.nationthailand.com/rss",
    describe: "Add to /api/news feed list.",
  },
  {
    id: "talkwalker",
    label: "Talkwalker Free Alerts",
    vendor: "Talkwalker",
    category: "vibes",
    status: "planned",
    describe: "Email-driven alerts; route via webhook into news feed.",
  },
  {
    id: "reddit-rss",
    label: "Reddit r/Thailand",
    vendor: "Reddit",
    category: "vibes",
    status: "ready",
    endpoint: "https://www.reddit.com/r/Thailand/.rss",
    describe: "Public RSS; cap to keyword match for Nakhon Si Thammarat / Khao Luang / Pak Phanang.",
  },
  {
    id: "google-trends",
    label: "Google Trends (local terms)",
    vendor: "Google",
    category: "vibes",
    status: "planned",
    describe: "Daily/hourly trend deltas for 'นครศรีธรรมราช', 'Pak Phanang', 'Khao Luang'; needs serpapi or unofficial pytrends.",
  },

  // ---- Open-data portals — POI + datasets ----
  {
    id: "open-meteo-aq-trend",
    label: "Open-Meteo AQ 8h forecast (trend)",
    vendor: "Open-Meteo",
    category: "environment",
    status: "live",
    endpoint: "https://air-quality-api.open-meteo.com/v1/air-quality (hourly forecast)",
    apiPath: "/api/air-quality/trend",
    pollSeconds: 900,
    describe: "Drives the prominent AQI badge — current + next 8h US AQI + PM2.5 sparkline + advisory band.",
  },

  // ---- Infrastructure ----
  {
    id: "pea-outages",
    label: "PEA electricity outages",
    vendor: "Provincial Electricity Authority",
    category: "infrastructure",
    status: "planned",
    endpoint: "https://www.pea.co.th/",
    describe: "Scheduled outage notices for the Nakhon Si Thammarat service area; scrape into incident layer when timing intersects business hours.",
  },
  {
    id: "pwa-water",
    label: "PWA water outage notices",
    vendor: "Provincial Waterworks Authority",
    category: "infrastructure",
    status: "planned",
    endpoint: "https://www.pwa.co.th/",
    describe: "Maintenance announcements affecting the Nakhon Si Thammarat municipal supply.",
  },

  // ---- Global markets — FMP + FRED ----
  {
    id: "fmp-markets",
    label: "FMP — global indices, forex, commodities",
    vendor: "Financial Modeling Prep",
    category: "vibes",
    status: "live",
    endpoint: "https://financialmodelingprep.com/api/v3/quote/...",
    apiPath: "/api/markets",
    keyEnv: "FMP_API_KEY",
    pollSeconds: 600,
    describe: "Live ticks for the SET (Stock Exchange of Thailand) + global indices (S&P, Nikkei, Hang Seng, FTSE, DAX), THB forex pairs, and commodities (WTI, Brent, Gold, Silver). Free tier 250/day.",
    docs: "https://site.financialmodelingprep.com/developer/docs",
  },
  {
    id: "fred-macro",
    label: "FRED — US macro + Thai baht series",
    vendor: "Federal Reserve Economic Data (St. Louis Fed)",
    category: "vibes",
    status: "live",
    endpoint: "https://api.stlouisfed.org/fred/series/observations?...",
    apiPath: "/api/markets",
    keyEnv: "FRED_API_KEY",
    pollSeconds: 600,
    describe: "Daily series: DGS10 (US 10Y yield), DGS2 (2Y), VIXCLS (volatility), DEXTHUS (THB/USD), DCOILWTICO (WTI). 120k calls/day.",
    docs: "https://fred.stlouisfed.org/docs/api/fred/",
  },

  // ---- Added 2026-05-17 from regional AQ research ----
  {
    id: "aqicn-nst",
    label: "AQICN Nakhon Si Thammarat stations (real-time)",
    vendor: "World Air Quality Index Project",
    category: "environment",
    status: "ready",
    endpoint: "https://api.waqi.info/feed/{station}/?token={AQICN_TOKEN}",
    keyEnv: "AQICN_TOKEN",
    pollSeconds: 900,
    describe: "Authoritative Southern Thailand AQ — nearest PCD station network to Nakhon Si Thammarat. Register free at aqicn.org/data-platform/token.",
    docs: "https://aqicn.org/api/",
  },
  {
    id: "data-go-th-points",
    label: "data.go.th — curated POIs (NST)",
    vendor: "DGA + curated",
    category: "open-data",
    status: "live",
    apiPath: "/api/datago/points",
    describe: "Curated geocoded POIs across health, education, religion, government, markets and police in Nakhon Si Thammarat province — sourced from data.go.th CKAN exports.",
    docs: "https://data.go.th/dataset",
  },
  {
    id: "data-go-th-datasets",
    label: "data.go.th — dataset index",
    vendor: "DGA (Digital Government Agency)",
    category: "open-data",
    status: "live",
    endpoint: "https://data.go.th/api/3/action/package_search",
    apiPath: "/api/datago/datasets",
    pollSeconds: 3600,
    describe: "Curated Nakhon Si Thammarat CKAN datasets (MoPH, MoE, DLA, DRA, RTP, PCD, EGAT dams, TAT, NSO, MoTS) plus live CKAN search on นครศรีธรรมราช.",
    docs: "https://data.go.th/dataset",
  },
  // ---- Nakhon Si Thammarat government dashboards ----
  {
    id: "nst-bi",
    label: "Nakhon Si Thammarat Provincial BI dashboard",
    vendor: "Nakhon Si Thammarat Provincial Office",
    category: "open-data",
    status: "research",
    endpoint: "https://www.nakhonsithammarat.go.th",
    describe: "Nakhon Si Thammarat province's public information + planning indicators. Behind redirect; auth flow needed to embed live.",
    docs: "https://www.nakhonsithammarat.go.th",
  },
  {
    id: "citydata-nst",
    label: "CityData — Smart City Data Platform (NST)",
    vendor: "depa Smart City Data Platform",
    category: "open-data",
    status: "research",
    endpoint: "https://www.citydata.in.th/",
    describe: "depa-hosted Smart City Data Platform. Check for a Nakhon Si Thammarat public dashboard with municipal indicators downloadable as CSV.",
    docs: "https://www.citydata.in.th/",
  },
  {
    id: "nst-nso",
    label: "Nakhon Si Thammarat Provincial Statistics Office",
    vendor: "NSO Thailand · Nakhon Si Thammarat branch",
    category: "open-data",
    status: "research",
    endpoint: "https://nakhonsithammarat.nso.go.th",
    describe: "Provincial statistics: population, household income, labour, agriculture (rubber, fruit, fisheries), education, public health. Updated quarterly.",
    docs: "https://nakhonsithammarat.nso.go.th",
  },
  {
    id: "nst-gov-news",
    label: "Nakhon Si Thammarat provincial government news",
    vendor: "Nakhon Si Thammarat Provincial Office",
    category: "vibes",
    status: "research",
    endpoint: "https://www.nakhonsithammarat.go.th",
    describe: "Official provincial announcement page. Behind anti-bot — needs headless browser or API key to ingest.",
    docs: "https://www.nakhonsithammarat.go.th",
  },
  {
    id: "dla-opendata",
    label: "DLA Open Data — local administration",
    vendor: "Department of Local Administration",
    category: "open-data",
    status: "research",
    endpoint: "https://opendata.dla.go.th",
    describe: "Local-government datasets nationwide: municipal budgets, staffing, project tracking, OSCC integration. CKAN-style portal.",
    docs: "https://opendata.dla.go.th",
  },
  {
    id: "nso-provincial",
    label: "NSO National Statistical Office",
    vendor: "Office of the Prime Minister",
    category: "open-data",
    status: "research",
    endpoint: "https://www.nso.go.th/nsoweb/official_stat/province/m",
    describe: "Official provincial statistics across Thailand — economy, social, environment, governance indicators.",
    docs: "https://www.nso.go.th/nsoweb/official_stat/province/m?set_lang=en",
  },
  {
    id: "aqicn-nst-station",
    label: "AQICN Nakhon Si Thammarat station",
    vendor: "World Air Quality Index project",
    category: "environment",
    status: "live",
    keyEnv: "AQICN_TOKEN",
    endpoint: "https://aqicn.org/city/thailand/nakhonsithammarat/",
    apiPath: "/api/air-quality/aqicn",
    describe: "Real-time AQI from Thailand's Pollution Control Department nearest station. Cross-validates and supplements Open-Meteo AQ grid. Requires AQICN_TOKEN (free at aqicn.org/data-platform/token).",
    docs: "https://aqicn.org/api/",
  },
  {
    id: "open-dev-mekong",
    label: "Open Development Thailand (Mekong)",
    vendor: "ODT / Mekong data hub",
    category: "open-data",
    status: "research",
    endpoint: "https://data.laos.opendevelopmentmekong.net/en/organization/thailand-organization",
    describe: "Cross-border spatial + sectoral datasets covering Thailand including Southern-region land use, water, and demographics.",
    docs: "https://opendevelopmentmekong.net",
  },
  // ---- Social ----
  {
    id: "fb-nst-municipality",
    label: "Facebook · Nakhon Si Thammarat City Municipality page",
    vendor: "Meta (page plugin embed)",
    category: "vibes",
    status: "ready",
    apiPath: "/api/social/facebook",
    keyEnv: "FACEBOOK_PAGE_TOKEN",
    pollSeconds: 600,
    describe: "Official municipality page. No-auth Meta iframe embed always works; set FACEBOOK_PAGE_TOKEN + FACEBOOK_PAGE_ID for richer server-side post data.",
  },
  // ---- Flood / hydrology ----
  {
    id: "open-meteo-flood",
    label: "Open-Meteo Flood — Tha Dee canal discharge",
    vendor: "Open-Meteo (GloFAS)",
    category: "environment",
    status: "live",
    endpoint: "https://flood-api.open-meteo.com/v1/flood",
    apiPath: "/api/flood/gauges",
    pollSeconds: 10800,
    describe: "GloFAS daily river-discharge (m³/s) for the Tha Dee canal (คลองท่าดี) draining Khao Luang into Nakhon Si Thammarat city + the Pak Phanang basin. Free, no key. Proxy for flood-gauge status and runoff trend.",
    docs: "https://open-meteo.com/en/docs/flood-api",
  },
  // ── GISTDA (Geo-Informatics & Space Technology Development Agency) ──────

  {
    id: "gistda-poi-digital-twin",
    label: "GISTDA POI Digital Twin",
    vendor: "GISTDA",
    category: "open-data",
    status: "live",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/POI_Map_Service/MapServer/0",
    keyEnv: "GISTDA_API_KEY",
    describe: "100K+ national POIs: government, schools, temples, hotels, restaurants, sports, hospitals. Official Thai+English names + road names + disability access. ArcGIS FeatureServer, no auth needed for read.",
    docs: "https://gistdaportal.gistda.or.th",
  },
  {
    id: "gistda-solar-lod2",
    label: "GISTDA LOD2 Solar irradiance",
    vendor: "GISTDA",
    category: "environment",
    status: "research",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/GISDTA_BLDGLOD2_Solar_TimeSlider_Chonburi_Month/MapServer",
    keyEnv: "GISTDA_API_KEY",
    describe: "Monthly solar irradiance (kWh/m²) per LOD2 building footprint. 12-month time-slider. GISTDA's public LOD2-solar tilesets currently cover only pilot provinces — returns empty for the Nakhon Si Thammarat bbox until a Southern tileset ships (graceful fallback). Fields: sun_irr, roof type, building type, height, area.",
    docs: "https://gistdaportal.gistda.or.th",
  },
  {
    id: "gistda-admin-bounds",
    label: "GISTDA Administrative Boundaries",
    vendor: "GISTDA",
    category: "open-data",
    status: "research",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/ข้อมูลเขตการปกครอง/MapServer",
    keyEnv: "GISTDA_API_KEY",
    describe: "Official Thai admin boundaries: province, district (อำเภอ), tambon (ตำบล), village (หมู่บ้าน). 5 ArcGIS layers. Pending correct bbox/filter to return Nakhon Si Thammarat sub-units.",
  },
  {
    id: "gistda-pm25-idw",
    label: "GISTDA PM2.5 / PM10 / CO2 / NOx IDW rasters",
    vendor: "GISTDA",
    category: "environment",
    status: "ready",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/Idw_02_PM2_Index/MapServer",
    keyEnv: "GISTDA_API_KEY",
    describe: "Inverse Distance Weighted interpolated air-quality rasters for Thailand (PM1, PM2.5, PM4, PM10, CO2, NOx). Coverage centres on NE/central Thailand — verify extent before using for Nakhon Si Thammarat.",
  },
  {
    id: "gistda-waste-2611",
    label: "GISTDA Waste Disposal Sites (2,611 nationwide)",
    vendor: "GISTDA",
    category: "open-data",
    status: "ready",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/2611landfills/FeatureServer",
    keyEnv: "GISTDA_API_KEY",
    describe: "All 2,611 registered waste disposal / landfill sites in Thailand. Fields: site name, province, owner type, management method, area. Filter by province code when wiring the Nakhon Si Thammarat layer.",
  },
  {
    id: "gistda-illegal-race",
    label: "GISTDA Illegal Street Racing Hotspots",
    vendor: "GISTDA",
    category: "incidents",
    status: "research",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/IllegalRace/FeatureServer",
    keyEnv: "GISTDA_API_KEY",
    describe: "Point data of known illegal street racing locations + incidents with date + intensity. Safety layer — mayor can target police deployment.",
  },
  {
    id: "gistda-theos2",
    label: "GISTDA THEOS-2 Satellite (50 cm resolution)",
    vendor: "GISTDA",
    category: "imagery",
    status: "ready",
    endpoint: "https://gistdaportal.gistda.or.th",
    keyEnv: "GISTDA_API_KEY",
    describe: "Thailand's own Earth observation satellite. 50 cm resolution. GISTDA_API_KEY enables tasking requests for Nakhon Si Thammarat: flood monitoring, Khao Luang watershed surveys, agricultural (rubber + fruit) mapping, disaster response.",
    docs: "https://www.gistda.or.th/theos-2",
  },
  {
    id: "gistda-lst",
    label: "GISTDA Land Surface Temperature (CCO)",
    vendor: "GISTDA",
    category: "environment",
    status: "research",
    endpoint: "https://gistdaportal.gistda.or.th/arcgis/rest/services/LST_CCO_tif/MapServer",
    keyEnv: "GISTDA_API_KEY",
    describe: "Land Surface Temperature raster from Landsat/THEOS — Climate Change Observatory series. Urban heat island mapping for Nakhon Si Thammarat city + surrounding districts.",
  },
  {
    id: "gistda-unl",
    label: "GISTDA UNL (Thai Address Geocoding)",
    vendor: "GISTDA",
    category: "open-data",
    status: "research",
    keyEnv: "GISTDA_API_KEY",
    describe: "GISTDA's Thai address geocoding service — convert Thai addresses to lat/lng coordinates. Endpoint under investigation; API key format may differ from ArcGIS services.",
    docs: "https://www.gistda.or.th",
  },

];

export function sourcesByStatus(status: SourceStatus) {
  return SOURCE_CATALOG.filter((s) => s.status === status);
}

export function sourcesByCategory(category: SourceCategory) {
  return SOURCE_CATALOG.filter((s) => s.category === category);
}
